### ISSUE TITLE
Opis Closure 4.x is available for testing

### ISSUE THREAD

**Issue by msarca** [opis/closure#59] opened 2020-06-09 11:57 UTC
Hi, everyone! 

I'm happy to announce that we are about to launch [a new version of Opis Closure](/opis/closure/tree/4.x). 

This version targets PHP +7.4 and use FFI to make closures truly serializable, without wrapping them inside a `SerializableClosure` object. This means that you no longer need to adapt your library's logic in order to have serializable closures. One line of code and closures will become serializable.

Please give it a try and let us know if you have encountered any issues while testing.

**Comment by xepozz** [comment] 2020-06-11 14:42
> @xepozz If you believe you have discovered a bug, please open a new issue so we could treat it properly. Also, you must be aware that Opis Closure 4.x is incompatible with 3.x and generates the code differently than you might expect. Our goal is to make closures serializable. If you are using this library for different purposes, than it might not be the most appropriate tool.

We are using this package for serializing/unserializing standalone closures and closures in a properties.

**Comment by msarca** [comment] 2020-06-11 15:24
@xepozz Please open a new issue and provide the most basic example that can be reproduced. Thanks.

**Comment by msarca** [comment] 2020-06-11 16:00
@xepozz I did take a look at your test results and the first thing that struck me was [this](https://github.com/yiisoft/composer-config-plugin/pull/82/checks?check_run_id=759176657#step:12:455): `Error: Class 'Environment\Serializer\CustomSerializer' not found`. Incidentally that is [the class](https://github.com/yiisoft/composer-config-plugin/pull/82/commits/8dedfe1d1e7047178e3543e804ca943b82d37047#diff-43a8d0faf6ba4f9a169c48ff56b19c18) where closure serialization was supposed to be happen.

**Comment by xepozz** [comment] 2020-06-14 17:21
> @xepozz I did take a look at your test results and the first thing that struck me was [this](https://github.com/yiisoft/composer-config-plugin/pull/82/checks?check_run_id=759176657#step:12:455): `Error: Class 'Environment\Serializer\CustomSerializer' not found`. Incidentally that is [the class](https://github.com/yiisoft/composer-config-plugin/pull/82/commits/8dedfe1d1e7047178e3543e804ca943b82d37047#diff-43a8d0faf6ba4f9a169c48ff56b19c18) where closure serialization was supposed to be happen.

I've fixed it

**Comment by sorinsarca** [comment] 2020-07-02 10:53
We added PHP 8 support

**Comment by taylorotwell** [comment] 2020-07-06 21:47
A **huge** feature of Laravel is queued Closures with proper ORM model serialization / deserialization when the models are part of the `use` portion of the Closure. We accomplished this in previous versions of Opis by overwriting methods that I had PR'd to Opis: https://github.com/opis/closure/pull/21

Can this still be accomplished in 4.x? Again, this is a very large and widely used feature of Laravel so if it's not planned to be supported for 4.x we will likely be forced to fork 3.x and maintain that version ourselves unfortunately. 😬

**Comment by sorinsarca** [comment] 2020-07-07 11:49
> Can this still be accomplished in 4.x?

Not at this time, but a similar mechanism can be added in 5 minutes. 

However, in 4.x there are no wrappers, meaning that `transformUseVariables`/`resolveUseVariables` handlers will apply globally. 

Also, since we removed the wrappers you view a closure as other data type, like an array (from serialization/unserialization perspective), so this should work:

```php
$a = function () use ($laravalModel, $laravelCollection) {};
$b = [$laravelModel, $laravelCollection]; //  array serialization is handled by PHP, so you don't have transform/resolve handlers

unserialize(serialize($a)); // works because we have transform/resolve handlers
unserialize(serialize($b)); // should also work. 
```
If it doesn't work properly then the problem is not related to opis/closure (in my opinion, @msarca what do you think?).

> Again, this is a very large and widely used feature of Laravel so if it's not planned to be supported for 4.x we will likely be forced to fork 3.x and maintain that version ourselves unfortunately.

We just added @GrahamCampbell to opis/closure team to help maintain version 3.x for laravel as long as necessary (see #63).

**Comment by taylorotwell** [comment] 2020-07-07 14:54
It would not be a significant problem for us for those handlers to apply globally I don't think.

**Comment by mnapoli** [comment] 2021-07-05 18:46
Hey, PHP-DI maintainer here 👋  We're using opis/closure too, and I'm worried about the usage of FFI: AFAIK that extension isn't installed by default, is that correct?

@taylorotwell is the FFI requirement an issue with Laravel?

**Comment by msarca** [comment] 2021-07-05 19:52
@mnapoli We are also dependant on `ext-tokenizer` #92, and nobody ever complained 😅. The FFI extension is a bundled extension, just like `ext-tokenizer`, `ext-pdo`, or `ext-mbstring`, and I don't think it will be an issue.

**Comment by SvenRtbg** [comment] 2021-07-06 09:53
The PHP dpcumentation is still warning that the FFI extension is experimental. Using the extension requires the "libffi" library to be installed, and PHP has to be compiled using "--with-ffi".

I have my doubts that distributions will do that by default, and would consider relying on that extension to be risky.

**Comment by SvenRtbg** [comment] 2021-07-09 08:46
I got feedback from my ops team: Suse Linux is not yet providing the FFI extension. If we'd ask them to provide it, it would go only into their latest release, which is SLES15SP3.

**Comment by thorewi** [comment] 2022-01-21 15:40
Hi,

I guess version 4.x doesn't work with PHP 8.1, at least for me.

Dockerfile:
```
FROM php:8.1-fpm
RUN docker-php-source extract \
&& apt-get update \
&& apt-get install libffi-dev && docker-php-ext-configure ffi --with-ffi && docker-php-ext-install ffi \
&& docker-php-source delete
```

php.ini:
```
extension=ffi.so
ffi.enable = true
```

test.php
```
<?php

declare(strict_types=1);

require __DIR__ . '/../vendor/autoload.php';

\Opis\Closure\Library::init();

$f = fn() => 'Hello';
$data = serialize($f);
$g = unserialize($data);
echo $g(); //> Hello
```

Output:
```
tomaskudelka@tomas-air sandbox % php www/index.php

Fatal error: Uncaught Exception: Serialization of 'Closure' is not allowed in /var/www/html/www/index.php:11
Stack trace:
#0 /var/www/html/www/index.php(11): serialize(Object(Closure))
#1 {main}
  thrown in /var/www/html/www/index.php on line 11
```

With PHP 8.0 and same configuration everything works fine.

**Comment by driesvints** [comment] 2022-01-21 16:21
@thorewi take a look at https://github.com/laravel/serializable-closure

**Comment by msarca** [comment] 2022-01-21 16:28
@driesvints removed your comment for being off topic

**Comment by driesvints** [comment] 2022-01-21 16:30
@msarca sure, it's your privilege to maintain this repo how you prefer. Was just trying to help @thorewi

**Comment by thorewi** [comment] 2022-01-21 16:44
@driesvints yes, thank you, I know the another library...

**Comment by frodeborli** [comment] 2024-08-20 18:43
> A **huge** feature of Laravel is queued Closures with proper ORM model serialization / deserialization when the models are part of the `use` portion of the Closure. We accomplished this in previous versions of Opis by overwriting methods that I had PR'd to Opis...
> 
> 
> 
> My original PR to Opis: https://github.com/opis/closure/pull/21
> 
> 
> 
> Our overwritten methods can be seen here: https://github.com/illuminate/queue/blob/master/SerializableClosure.php
> 
> 
> 
> Can this still be accomplished in 4.x? Again, this is a very large and widely used feature of Laravel so if it's not planned to be supported for 4.x we will likely be forced to fork 3.x and maintain that version ourselves unfortunately. 😬 

I have written a new serialization library that supports serializing closures without wrapping them. Also it supports serializing readonly Closure properties. I haven't released it yet (it will be part of another library instead) but if there is need I can.

**Comment by sorinsarca** [comment] 2024-12-28 21:51
Version 4.0 was released without ffi dependency. It is a full rewrite of the library to support latest PHP 8.x features.

**Closed by sorinsarca** 2024-12-28 21:51 UTC
